name: Unit tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20', '1.21' ]
    name: Go ${{ matrix.go }} tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Run go test
        run: go test -v ./...

